import { Story, Language } from './types';

export const TRANSLATIONS = {
  en: {
    nav: {
      home: "Home",
      library: "Story Library",
      design: "Design Your Story",
      admin: "Admin Dashboard",
      login: "Login",
      logout: "Logout",
      theme: "Toggle Theme",
      support: "Support Us",
      adminPanel: "Admin Panel",
      signIn: "Sign In",
      myDashboard: "My Dashboard",
      supportProject: "Support the Project",
      lightMode: "Switch to Light Mode",
      darkMode: "Switch to Dark Mode",
      languages: {
        ar: "Arabic",
        en: "English",
        fr: "French"
      }
    },
    seo: {
      home: {
        title: "Home",
        description: "Jeen Arabi - A bilingual interactive storytelling platform for children. Read, create, and learn in Arabic, English, and French.",
        keywords: "children stories, bilingual, arabic stories, kids education, interactive reading"
      },
      library: {
        title: "Story Library",
        siteName: "Jeen Arabi Library",
        description: "Explore our collection of bilingual stories for children. Filter by age, language, and topic.",
        keywords: "story library, kids books, reading, education"
      },
      design: {
        title: "Design Studio",
        description: "Create your own magical stories with our interactive design studio. Use stickers, draw, and let AI help you write.",
        keywords: "create stories, kids writing, imagination, drawing"
      },
      login: {
        title: "Login",
        description: "Login to Jeen Arabi to manage stories and subscribers.",
        keywords: "login, admin, dashboard"
      },
      support: {
        title: "Support Us",
        description: "Support Jeen Arabi's mission to provide high-quality bilingual stories for children. Help us expand our magical library.",
        keywords: "support, donate, children education, bilingual stories"
      }
    },
    hero: {
      title: "Discover a World of Stories",
      subtitle: "Bilingual adventures for curious minds. Read, learn, and create.",
      cta: "Start Reading",
      secondaryCta: "Create a Story",
      badge: "Interactive Learning Platform",
      features: [
        { title: "Bilingual Stories", desc: "Switch between Arabic and English instantly.", icon: "🌍" },
        { title: "Interactive Design", desc: "Create your own covers and stories.", icon: "🎨" },
        { title: "Safe & Secure", desc: "Ad-free environment for kids.", icon: "🛡️" }
      ]
    },
    library: {
      title: "Our Stories",
      filterAge: "Filter by Age",
      filterLang: "Filter by Language",
      filterTags: "Filter by Topic",
      read: "Read Story",
      download: "Download PDF",
      all: "All",
      close: "Close Viewer",
      downloads: "Downloads",
      views: "Views",
      age: "Age",
      categories: "Categories",
      storiesAvailable: "Stories Available",
      loadingStory: "Loading Story...",
      noFavoritesTitle: "No favorites yet!",
      noFavoritesDesc: "Browse the library and heart the stories you love to find them here.",
      noResultsTitle: "No Stories Found",
      noResultsDesc: "Try adjusting your filters or browse all available stories.",
      exploreAll: "Explore All Stories",
      storyFinished: "Awesome! You've finished the story! 🎉",
      share: "Share",
      narrator: "Narrator",
      music: "Music",
      zoom: "Zoom/Fullscreen",
      mute: "Mute/Unmute",
      prevPage: "Previous Page",
      nextPage: "Next Page",
      shareSuccess: "Story link copied!",
      musicError: "Please interact with the page to play music",
      errorTitle: "Sorry, an error occurred",
      retry: "Retry"
    },
    design: {
      title: "Design Your First Story",
      subtitle: "Drag stickers, add a title, and let our AI write the story for you!",
      tools: "Tools",
      addText: "Add Text",
      addSticker: "Add Sticker",
      generate: "Write Story with AI",
      download: "Download Cover",
      placeholderTitle: "My Magical Adventure",
      generating: "Magic happening...",
      storyDetails: "Story Details",
      authorName: "Author Name",
      addElements: "Add Elements",
      text: "Text",
      draw: "Draw",
      stickers: "Stickers",
      page: "Page",
      of: "of",
      deletePage: "Delete Page",
      newPage: "New Page",
      startDesigning: "Start Designing!",
      dragStickers: "Drag stickers, add text, or draw something.",
      aiStory: "AI Story",
      drawingPad: "Drawing Pad",
      addToStory: "Add to Story",
      exportPdf: "Export PDF",
      generatingBtn: "Generating...",
      toastMinPage: "You must have at least one page.",
      promptText: "Enter your text:",
      toastDrawingAdded: "Drawing added to story!",
      toastGeneratingPdf: "Generating PDF Book...",
      toastPdfDownloaded: "PDF Downloaded!",
      toastPdfFailed: "Failed to generate PDF",
      pdfPage: "Page",
      saveToProfile: "Save to Profile",
      drawing: "Drawing",
      preview: "Preview",
      enterText: "Enter your text",
      confirm: "Confirm",
      cancel: "Cancel",
      delete: "Delete",
      loginToSave: "Please log in to save your design",
      enterTitle: "Please enter a title for the story",
      savingDesign: "Saving design...",
      saveDesignSuccess: "Design saved to your profile! ✨",
      saveDesignFail: "Failed to save design",
      previewReady: "Preview ready",
      pagesLabel: "Pages",
      ofLabel: "of"
    },
    admin: {
      title: "Admin Dashboard",
      stories: "Manage Stories",
      subscribers: "Subscribers",
      analytics: "Analytics",
      addStory: "Add New Story",
      edit: "Edit",
      delete: "Delete",
      save: "Save Story",
      saveCategory: "Save Category",
      cancel: "Cancel",
      addSubscriber: "Add Subscriber",
      gdprLabel: "I confirm that I have obtained explicit consent from this user to store their data and send them story updates in accordance with GDPR regulations.",
      loginTitle: "Admin Login",
      loginBtn: "Login",
      categories: "Categories",
      manageCategories: "Manage Categories",
      addCategory: "Add Category",
      editCategory: "Edit Category",
      nameEn: "Name (English)",
      nameAr: "Name (Arabic)",
      descEn: "Description (English)",
      descAr: "Description (Arabic)",
      availableLangs: "Available Languages",
      createStory: "Create Story",
      editStory: "Edit Story",
      storyTitle: "Story Title",
      storyDesc: "Description",
      ageGroup: "Age Group",
      coverImage: "Cover Image",
      uploadPdf: "Upload PDF",
      uploadCover: "Upload Cover",
      users: "Users",
      manageUsers: "Manage Users",
      deleteUser: "Delete User",
      confirmDeleteUser: "Are you sure you want to delete this user?",
      deleteUserSuccess: "User deleted successfully",
      deleteAdminError: "Cannot delete admin users",
      fetchUsersError: "Failed to load users",
      totalStories: "Total Stories",
      totalViews: "Total Views",
      activeSubscribers: "Active Subscribers",
      uniqueTags: "Unique Tags",
      storyViews: "Story Views",
      ageDistribution: "Age Group Distribution",
      ageToddlers: "Toddlers (3-5)",
      ageEarly: "Early Readers (6-8)",
      ageYoung: "Young Readers (9-12)",
      contentSuffix: "Content",
      uploadTitleCover: "Click to Upload Cover",
      tagsLabel: "Tags (Categories)",
      tagNamePlaceholder: "Add tag...",
      deleteStoryConfirm: "Are you sure you want to delete this story?",
      deleteStorySuccess: "Story deleted",
      deleteStoryError: "Failed to delete story",
      storySavedSuccess: "Story saved successfully",
      storySavedError: "Failed to save story",
      uploadSuccess: "Uploaded successfully",
      uploadError: "Upload failed",
      uploading: "Uploading...",
      processing: "Processing files...",
      validationTitle: "Please enter a title for at least one of the selected languages.",
      validationCover: "Please upload a cover image.",
      validationPdf: "Please upload a PDF file.",
      searchPlaceholder: "Search stories...",
      allCategories: "All Categories",
      anyLanguage: "Any Language",
      reset: "Reset",
      untitled: "Untitled",
      downloads: "Downloads",
      noStoriesFound: "No stories found matching your search.",
      usersManagement: "Users Management",
      user: "User",
      email: "Email",
      role: "Role",
      joined: "Joined",
      actions: "Actions",
      noUsers: "No users to display",
      fullName: "Full Name",
      subscribersListTitle: "Subscribers List",
      platformSettings: "Platform Settings",
      saving: "Saving...",
      saveAll: "Save All",
      supportLinks: "Support Links",
      siteMessages: "Site Messages",
      welcomeMsgAr: "Welcome Message (AR)",
      welcomeMsgEn: "Welcome Message (EN)",
      refresh: "Refresh",
      exportUsers: "Export Users"
    },
    analytics: {
      title: "Analytics Dashboard",
      dateRange: "Date Range",
      refresh: "Refresh",
      uniqueVisitors: "Unique Visitors",
      pageViews: "Page Views",
      registeredUsers: "Registered Users",
      avgPagesSession: "Avg. Pages/Session",
      dailyGrowth: "Daily Growth",
      visitors: "Visitors",
      deviceBreakdown: "Device Breakdown",
      topBrowsers: "Top Browsers",
      geoDistribution: "Geographic Distribution",
      topCountries: "Top Countries",
      topCities: "Top Cities",
      trafficSources: "Traffic Sources",
      utmCampaigns: "UTM Campaigns",
      source: "Source",
      medium: "Medium",
      directTraffic: "Direct Traffic",
      referrals: "Referrals",
      topStories: "Top Performing Stories",
      story: "Story",
      uniqueViews: "Unique Views",
      totalViews: "Total Views",
      socialMediaPerformance: "Social Media Performance",
      platform: "Platform",
      clicks: "Clicks",
      conversions: "Conversions",
      mostSharedStories: "Most Shared Stories",
      loading: "Loading..."
    },
    reviews: {
      title: "Customer Reviews",
      subtitle: "Discover what parents and children say about Jeen Arabi",
      writeReview: "Write a Review",
      rateStory: "Rate this Story",
      rating: "Rating",
      yourReview: "Your Review",
      submit: "Submit",
      thankYou: "Thank you for your review! It will be published after approval.",
      topStories: "Top Stories",
      seeMore: "See More",
      guestName: "Your Name",
      chooseAvatar: "Choose Your Avatar"
    },
    dashboard: {
      title: "My Dashboard",
      welcome: "Welcome, {name}!",
      subtitle: "Ready for a new adventure today?",
      quickLibrary: "Browse Library",
      quickDesign: "Design a Story",
      myFavorites: "My Favorites",
      noFavorites: "No favorites yet. Start exploring!",
      viewInLibrary: "View Favorites in Library",
      stats: "My Stats",
      readStories: "Read Stories",
      myDesigns: "My Designs",
      tipTitle: "Tip of the Day",
      tipContent: "Reading 15 minutes a day opens up horizons of imagination!",
      settings: "Account Settings",
      readingMinutes: "Reading Minutes",
      completedStories: "Completed Stories",
      continueReading: "Continue Reading",
      startNow: "Start Now",
      page: "Page",
      scrollToTop: "Go to Top",
      friend: "Friend",
      goToLibrary: "Go to Library"
    },
    footer: {
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      rights: "All rights reserved to Jeen Arabi Library"
    },
    privacy: {
      title: "Privacy Policy",
      lastUpdated: "Last updated: January 2026",
      intro: "Your privacy is important to us. This policy explains how we collect, use, and protect your information.",
      sections: [
        { title: "Data Collection", content: "We collect only the necessary information to provide our services, such as your username and email address." },
        { title: "Data Usage", content: "Your data is used to personalize your experience, provide support, and improve our magical stories." },
        { title: "Security", content: "We implement robust security measures to protect your data from unauthorized access." }
      ]
    },
    terms: {
      title: "Terms of Service",
      lastUpdated: "Last updated: January 2026",
      intro: "By using Jeen Arabi, you agree to the following terms and conditions.",
      sections: [
        { title: "Acceptable Use", content: "You agree to use our platform for educational and creative purposes only." },
        { title: "Account Safety", content: "You are responsible for maintaining the confidentiality of your account." },
        { title: "Content Ownership", content: "All stories and designs created on the platform are protected by copyright." }
      ]
    },
    support: {
      title: "Support Our Magical Journey",
      parentTitle: "Support the Magical Journey of Stories",
      subtitle: "We believe everyone deserves a magical story that inspires them. Your support helps us provide more creativity and knowledge for free for everyone.",
      parentSubtitle: "Your support doesn't just develop the platform; it ensures magical stories remain available for children worldwide, with a special focus on Arabic-speaking kids.",
      methodCoffee: "Buy Me A Coffee",
      methodCoffeeDesc: "A simple and quick way to support the continuity of our stories.",
      methodCoffeeBtn: "Support with Coffee",
      methodPaypal: "Donate via PayPal",
      methodPaypalDesc: "Direct and secure support to contribute to platform development.",
      methodPaypalBtn: "Donate Now",
      methodShare: "Spread the Magic",
      methodShareDesc: "Share the platform with your friends and family to support us.",
      methodShareBtn: "Share Website",
      impactTitle: "Why Support Jeen Arabi?",
      impactDesc: "Every donation, no matter how small, contributes to hosting costs, developing new features, and providing high-quality educational content for children around the world.",
      footerMsg: "Thank you for being part of our magical community ✨"
    },
    register: {
      title: "Create Account",
      subtitle: "Join the magical world of Jeen Arabi",
      username: "Username",
      email: "Email Address",
      password: "Password",
      btn: "Create Account",
      alreadyHave: "Already have an account?",
      login: "Sign In",
      success: "Account created successfully! Welcome ✨"
    },
    settings: {
      title: "Account Settings",
      personalInfo: "Personal Information",
      username: "Username",
      email: "Email Address",
      changePassword: "Change Password",
      oldPassword: "Current Password",
      newPassword: "New Password",
      confirmPassword: "Confirm New Password",
      updateBtn: "Update Profile",
      passwordBtn: "Update Password",
      successProfile: "Profile updated successfully!",
      successPassword: "Password updated successfully!",
      errorMatch: "Passwords do not match",
      dangerZone: "Danger Zone",
      deleteAccount: "Delete Account",
      deleteWarning: "Once you delete your account, there is no going back. Please be certain."
    }
  },
  ar: {
    nav: {
      home: "الرئيسية",
      library: "مكتبة القصص",
      design: "صمم قصتك",
      admin: "لوحة التحكم",
      login: "دخول",
      logout: "خروج",
      theme: "تغيير المظهر",
      support: "ادعمنا",
      adminPanel: "لوحة التحكم",
      signIn: "تسجيل الدخول",
      myDashboard: "لوحتي الخاصة",
      supportProject: "ادعم المشروع",
      lightMode: "التبديل للمظهر المضيء",
      darkMode: "التبديل للمظهر المظلم",
      languages: {
        ar: "العربية",
        en: "الإنجليزية",
        fr: "الفرنسية"
      }
    },
    seo: {
      home: {
        title: "الرئيسية",
        description: "جين عربي - منصة قصص تفاعلية ثنائية اللغة للأطفال. اقرأ، ابدع، وتعلم بالعربية والإنجليزية والفرنسية.",
        keywords: "قصص أطفال، ثنائية اللغة، قصص عربية، تعليم أطفال، قراءة تفاعلية"
      },
      library: {
        title: "مكتبة القصص",
        siteName: "مكتبة جين عربي",
        description: "استكشف مجموعتنا من القصص ثنائية اللغة للأطفال. تصفح حسب العمر، اللغة، والموضوع.",
        keywords: "مكتبة قصص، كتب أطفال، قراءة، تعليم"
      },
      design: {
        title: "استوديو التصميم",
        description: "صمم قصصك السحرية الخاصة مع استوديو التصميم التفاعلي. استخدم الملصقات، ارسم، ودع الذكاء الاصطناعي يساعدك في الكتابة.",
        keywords: "تأليف قصص، كتابة للأطفال، خيال، رسم"
      },
      login: {
        title: "دخول",
        description: "تسجيل الدخول إلى جين عربي لإدارة القصص والمشتركين.",
        keywords: "دخول، مشرف، لوحة تحكم"
      },
      support: {
        title: "ادعمنا",
        description: "ادعم مهمة جين عربي لتوفير قصص ثنائية اللغة عالية الجودة للأطفال. ساعدنا في توسيع مكتبتنا السحرية.",
        keywords: "دعم، تبرع، تعليم الأطفال، قصص سحرية"
      }
    },
    hero: {
      title: "اكتشف عالماً من القصص",
      subtitle: "مغامرات متعددة اللغات للعقول الفضولية. اقرأ، تعلم، وابدع.",
      cta: "ابدأ القراءة",
      secondaryCta: "صمم قصة",
      badge: "منصة تعليمية تفاعلية",
      features: [
        { title: "قصص ثنائية اللغة", desc: "بدّل بين العربية والإنجليزية فوراً.", icon: "🌍" },
        { title: "تصميم تفاعلي", desc: "اصنع أغلفتك وقصصك الخاصة.", icon: "🎨" },
        { title: "آمن ومحمي", desc: "بيئة خالية من الإعلانات للأطفال.", icon: "🛡️" }
      ]
    },
    library: {
      title: "قصصنا",
      filterAge: "تصفية حسب العمر",
      filterLang: "تصفية حسب اللغة",
      filterTags: "تصفية حسب الموضوع",
      read: "اقرأ القصة",
      download: "تحميل PDF",
      all: "الكل",
      close: "إغلاق القصة",
      downloads: "التحميلات",
      views: "المشاهدات",
      age: "العمر",
      categories: "التصنيفات",
      storiesAvailable: "قصص متاحة",
      loadingStory: "جاري تحميل القصة...",
      noFavoritesTitle: "لم تضف أي قصص للمفضلة بعد",
      noFavoritesDesc: "تصفح المكتبة وأضف القصص التي تحبها لتجدها هنا دائماً.",
      noResultsTitle: "لم يتم العثور على نتائج",
      noResultsDesc: "جرّب تعديل الفلاتر أو تصفح كل القصص المتاحة.",
      exploreAll: "استكشاف كل القصص",
      storyFinished: "رائع! لقد أنهيت القصة 🎉",
      share: "مشاركة",
      narrator: "الراوي",
      music: "الموسيقى",
      zoom: "تكبير/تصغير",
      mute: "كتم الصوت",
      prevPage: "الصفحة السابقة",
      nextPage: "الصفحة التالية",
      shareSuccess: "تم نسخ رابط القصة!",
      musicError: "يرجى التفاعل مع الصفحة لتشغيل الموسيقى",
      errorTitle: "عذراً، حدث خطأ",
      retry: "إعادة المحاولة"
    },
    design: {
      title: "صمم قصتك الأولى",
      subtitle: "أضف الملصقات والعناوين، ودع الذكاء الاصطناعي يكتب القصة لك!",
      tools: "الأدوات",
      addText: "إضافة نص",
      addSticker: "أضف ملصق",
      generate: "اكتب القصة بالذكاء الاصطناعي",
      download: "حفظ الغلاف",
      placeholderTitle: "مغامرتي السحرية",
      generating: "السحر يحدث...",
      storyDetails: "تفاصيل القصة",
      authorName: "اسم المؤلف",
      addElements: "إضافة عناصر",
      text: "نص",
      draw: "رسم",
      stickers: "ملصقات",
      page: "صفحة",
      of: "من",
      deletePage: "حذف الصفحة",
      newPage: "صفحة جديدة",
      startDesigning: "ابدأ التصميم!",
      dragStickers: "اسحب الملصقات، أضف نصاً، أو ارسم شيئاً.",
      aiStory: "قصة الذكاء الاصطناعي",
      drawingPad: "لوحة الرسم",
      addToStory: "إضافة للقصة",
      exportPdf: "تصدير PDF",
      generatingBtn: "جاري التوليد...",
      toastMinPage: "يجب أن يكون لديك صفحة واحدة على الأقل.",
      promptText: "أدخل النص:",
      toastDrawingAdded: "تمت إضافة الرسم للقصة!",
      toastGeneratingPdf: "جاري إنشاء كتاب PDF...",
      toastPdfDownloaded: "تم تحميل PDF!",
      toastPdfFailed: "فشل إنشاء PDF",
      pdfWrittenBy: "تأليف ورسم:",
      pdfPage: "صفحة",
      saveToProfile: "حفظ في ملفي",
      drawing: "رسم",
      preview: "معاينة",
      enterText: "أدخل النص الخاص بك",
      confirm: "تأكيد",
      cancel: "إلغاء",
      delete: "حذف",
      loginToSave: "يرجى تسجيل الدخول لحفظ التصميم",
      enterTitle: "يرجى إدخال عنوان للقصة",
      savingDesign: "جاري حفظ التصميم...",
      saveDesignSuccess: "تم حفظ التصميم في ملفك الشخصي! ✨",
      saveDesignFail: "فشل حفظ التصميم",
      previewReady: "المعاينة جاهزة",
      pagesLabel: "الصفحات",
      ofLabel: "من"
    },
    admin: {
      title: "لوحة التحكم",
      stories: "إدارة القصص",
      subscribers: "المشتركين",
      analytics: "التحليلات",
      addStory: "إضافة قصة جديدة",
      edit: "تعديل",
      delete: "حذف",
      save: "حفظ القصة",
      saveCategory: "حفظ التصنيف",
      cancel: "إلغاء",
      addSubscriber: "إضافة مشترك",
      gdprLabel: "أؤكد أنني حصلت على موافقة صريحة من هذا المستخدم لتخزين بياناته وإرسال تحديثات القصص له وفقاً للوائح حماية البيانات.",
      loginTitle: "دخول المشرف",
      loginBtn: "دخول",
      categories: "التصنيفات",
      manageCategories: "إدارة التصنيفات",
      addCategory: "إضافة تصنيف",
      editCategory: "تعديل التصنيف",
      nameEn: "الاسم (إنجليزي)",
      nameAr: "الاسم (عربي)",
      descEn: "الوصف (إنجليزي)",
      descAr: "الوصف (عربي)",
      availableLangs: "اللغات المتاحة",
      createStory: "إنشاء قصة",
      editStory: "تعديل القصة",
      storyTitle: "عنوان القصة",
      storyDesc: "الوصف",
      ageGroup: "الفئة العمرية",
      coverImage: "صورة الغلاف",
      uploadPdf: "رفع ملف PDF",
      uploadCover: "رفع الغلاف",
      users: "المستخدمين",
      manageUsers: "إدارة المستخدمين",
      deleteUser: "حذف المستخدم",
      confirmDeleteUser: "هل أنت متأكد من حذف هذا المستخدم؟",
      deleteUserSuccess: "تم حذف المستخدم بنجاح",
      deleteAdminError: "لا يمكن حذف مستخدمي الإدارة",
      fetchUsersError: "فشل تحميل المستخدمين",
      totalStories: "إجمالي القصص",
      totalViews: "إجمالي المشاهدات",
      activeSubscribers: "المشتركون النشطون",
      uniqueTags: "أوسمة فريدة",
      storyViews: "مشاهدات القصص",
      ageDistribution: "توزيع الفئات العمرية",
      ageToddlers: "الصغار (3-5)",
      ageEarly: "القراء المبتدئون (6-8)",
      ageYoung: "القراء اليافعون (9-12)",
      contentSuffix: "محتوى",
      uploadTitleCover: "اضغط لرفع الغلاف",
      tagsLabel: "الأوسمة (التصنيفات)",
      tagNamePlaceholder: "أضف وسم...",
      deleteStoryConfirm: "هل أنت متأكد من حذف هذه القصة؟",
      deleteStorySuccess: "تم حذف القصة",
      deleteStoryError: "فشل حذف القصة",
      storySavedSuccess: "تم حفظ القصة بنجاح",
      storySavedError: "فشل حفظ القصة",
      uploadSuccess: "تم الرفع بنجاح",
      uploadError: "فشل الرفع",
      uploading: "جاري الرفع...",
      processing: "جاري معالجة الملفات...",
      validationTitle: "يرجى إدخال عنوان بلغة واحدة على الأقل من اللغات المختارة.",
      validationCover: "يرجى رفع صورة الغلاف.",
      validationPdf: "يرجى رفع ملف PDF.",
      searchPlaceholder: "بحث عن القصص...",
      allCategories: "جميع الفئات",
      anyLanguage: "أي لغة",
      reset: "إعادة تعيين",
      untitled: "بدون عنوان",
      downloads: "التحميلات",
      noStoriesFound: "لم يتم العثور على قصص تطابق بحثك.",
      usersManagement: "إدارة المستخدمين",
      user: "المستخدم",
      email: "البريد الإلكتروني",
      role: "الدور",
      joined: "تاريخ الانضمام",
      actions: "إجراءات",
      noUsers: "لا يوجد مستخدمون لعرضهم",
      fullName: "الاسم الكامل",
      subscribersListTitle: "قائمة المشتركين",
      platformSettings: "إعدادات المنصة",
      saving: "جاري الحفظ...",
      saveAll: "حفظ الكل",
      supportLinks: "روابط الدعم",
      siteMessages: "رسائل الموقع",
      welcomeMsgAr: "رسالة الترحيب (عربي)",
      welcomeMsgEn: "رسالة الترحيب (إنجليزي)",
      refresh: "تحديث",
      exportUsers: "تصدير المستخدمين"
    },
    analytics: {
      title: "لوحة التحليلات",
      dateRange: "نطاق التاريخ",
      refresh: "تحديث",
      uniqueVisitors: "زوار فريدون",
      pageViews: "مشاهدات الصفحات",
      registeredUsers: "مستخدمون مسجلون",
      avgPagesSession: "متوسط الصفحات / جلسة",
      dailyGrowth: "النمو اليومي",
      visitors: "الزوار",
      deviceBreakdown: "توزيع الأجهزة",
      topBrowsers: "أشهر المتصفحات",
      geoDistribution: "التوزيع الجغرافي",
      topCountries: "أفضل الدول",
      topCities: "أفضل المدن",
      trafficSources: "مصادر الزيارات",
      utmCampaigns: "حملات UTM",
      source: "المصدر",
      medium: "الوسيط",
      directTraffic: "زيارات مباشرة",
      referrals: "الإحالات",
      topStories: "أكثر القصص مشاهدة",
      story: "القصة",
      uniqueViews: "مشاهدات فريدة",
      totalViews: "المشاهدات الكلية",
      socialMediaPerformance: "أداء السوشال ميديا",
      platform: "المنصة",
      clicks: "النقرات",
      conversions: "التحويلات",
      mostSharedStories: "أكثر القصص مشاركة",
      loading: "جاري التحميل..."
    },
    reviews: {
      title: "آراء عملائنا",
      subtitle: "اكتشف ما يقوله الآباء والأطفال عن جين عربي",
      writeReview: "اكتب مراجعة",
      rateStory: "قيّم القصة",
      rating: "التقييم",
      yourReview: "مراجعتك",
      submit: "إرسال",
      thankYou: "شكراً لمراجعتك! سيتم نشرها بعد الموافقة.",
      topStories: "أشهر القصص",
      seeMore: "تصفح المزيد",
      guestName: "اسمك",
      chooseAvatar: "اختر صورتك الشخصية"
    },
    dashboard: {
      title: "لوحتي الخاصة",
      welcome: "أهلاً بك، {name}!",
      subtitle: "مستعد لمغامرة جديدة اليوم؟",
      quickLibrary: "تصفح المكتبة",
      quickDesign: "صمم قصة",
      myFavorites: "قصصي المفضلة",
      noFavorites: "لم تضف قصصاً للمفضلة بعد. ابدأ الاستكشاف!",
      viewInLibrary: "مشاهدة المفضلة في المكتبة",
      stats: "إحصائياتي",
      readStories: "قصص تمت قراءتها",
      myDesigns: "تصاميمي",
      tipTitle: "نصيحة اليوم",
      tipContent: "القراءة لـ 15 دقيقة يومياً تفتح لك آفاقاً من الخيال!",
      settings: "إعدادات الحساب",
      readingMinutes: "دقائق القراءة",
      completedStories: "قصص مكتملة",
      continueReading: "أكمل القراءة",
      startNow: "ابدأ الآن",
      page: "وصلت للصفحة",
      scrollToTop: "العودة للأعلى",
      friend: "صديقنا",
      goToLibrary: "اذهب للمكتبة"
    },
    footer: {
      privacy: "سياسة الخصوصية",
      terms: "شروط الخدمة",
      rights: "جميع الحقوق محفوظة لمكتبة جين عربي",
    },
    privacy: {
      title: "سياسة الخصوصية",
      lastUpdated: "آخر تحديث: يناير 2026",
      intro: "خصوصيتك تهمنا. توضح هذه السياسة كيفية جمعنا لمعلوماتك واستخدامها وحمايتها.",
      sections: [
        { title: "جمع البيانات", content: "نحن نجمع فقط المعلومات الضرورية لتقديم خدماتنا، مثل اسم المستخدم وبريدك الإلكتروني." },
        { title: "استخدام البيانات", content: "تستخدم بياناتك لتخصيص تجربتك، وتقديم الدعم، وتحسين قصصنا السحرية." },
        { title: "الأمان", content: "نحن نطبق إجراءات أمنية قوية لحماية بياناتك من الوصول غير المصرح به." }
      ]
    },
    terms: {
      title: "شروط الخدمة",
      lastUpdated: "آخر تحديث: يناير 2026",
      intro: "باستخدامك لموقع جين عربي، فإنك توافق على الشروط والأحكام التالية.",
      sections: [
        { title: "الاستخدام المقبول", content: "أنت توافق على استخدام منصتنا للأغراض التعليمية والإبداعية فقط." },
        { title: "أمان الحساب", content: "أنت مسؤول عن الحفاظ على سرية حسابك ومعلومات دخولك." },
        { title: "ملكية المحتوى", content: "جميع القصص والتصاميم التي يتم إنشاؤها على المنصة محمية بحقوق الطبع والنشر." }
      ]
    },
    support: {
      title: "ادعم رحلتنا السحرية",
      parentTitle: "ادعم رحلة القصص السحرية",
      subtitle: "نحن نؤمن بأن الجميع يستحق قصة سحرية تلهمه. دعمك يساعدنا على تقديم المزيد من الإبداع والمعرفة مجاناً للجميع.",
      parentSubtitle: "دعمكم لا يطور المنصة فحسب، بل يضمن بقاء القصص السحرية متاحة للأطفال حول العالم، مع اهتمام خاص بالطفل العربي.",
      methodCoffee: "اشترِ لي قهوة",
      methodCoffeeDesc: "طريقة بسيطة وسريعة لدعم استمرارية قصصنا.",
      methodCoffeeBtn: "ادعم بالقهوة",
      methodPaypal: "تبرع عبر PayPal",
      methodPaypalDesc: "دعم مباشر وآمن للمساهمة في تطوير المنصة.",
      methodPaypalBtn: "تبرع الآن",
      methodShare: "انشر السحر",
      methodShareDesc: "شارك المنصة مع أصدقائك وعائلتك لدعمنا.",
      methodShareBtn: "مشاركة الموقع",
      impactTitle: "لماذا ندعم جين عربي؟",
      impactDesc: "كل تبرع، مهما كان بسيطاً، يساهم في دفع تكاليف الاستضافة، تطوير ميزات جديدة، وتوفير محتوى تعليمي عالي الجودة للأطفال حول العالم.",
      footerMsg: "شكراً لكونك جزءاً من مجتمعنا السحري ✨"
    },
    register: {
      title: "إنشاء حساب جديد",
      subtitle: "انضم إلى عالم جين عربي السحري",
      username: "اسم المستخدم",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      btn: "إنشاء حساب",
      alreadyHave: "لديك حساب بالفعل؟",
      login: "سجل دخولك",
      success: "تم إنشاء الحساب بنجاح! أهلاً بك ✨"
    },
    settings: {
      title: "إعدادات الحساب",
      personalInfo: "المعلومات الشخصية",
      username: "اسم المستخدم",
      email: "البريد الإلكتروني",
      changePassword: "تغيير كلمة المرور",
      oldPassword: "كلمة المرور الحالية",
      newPassword: "كلمة المرور الجديدة",
      confirmPassword: "تأكيد كلمة المرور الجديدة",
      updateBtn: "تحديث الملف الشخصي",
      passwordBtn: "تحديث كلمة المرور",
      successProfile: "تم تحديث الملف الشخصي بنجاح!",
      successPassword: "تم تغيير كلمة المرور بنجاح!",
      errorMatch: "كلمات المرور غير متطابقة",
      dangerZone: "منطقة الخطر",
      deleteAccount: "حذف الحساب",
      deleteWarning: "بمجرد حذف حسابك، لن تتمكن من العودة. يرجى التأكد."
    }
  },
  fr: {
    nav: {
      home: "Accueil",
      library: "Bibliothèque",
      design: "Créer",
      admin: "Admin",
      login: "Connexion",
      logout: "Déconnexion",
      theme: "Changer de thème",
      support: "Soutenez-nous",
      adminPanel: "Tableau de Bord",
      signIn: "Se connecter",
      myDashboard: "Mon Tableau de Bord",
      supportProject: "Soutenir le Projet",
      lightMode: "Passer au Mode Clair",
      darkMode: "Passer au Mode Sombre",
      languages: {
        ar: "Arabe",
        en: "Anglais",
        fr: "Français"
      }
    },
    seo: {
      home: {
        title: "Accueil",
        description: "Jeen Arabi - Une plateforme de narration interactive bilingue pour les enfants. Lisez, créez et apprenez en arabe, anglais et français.",
        keywords: "histoires pour enfants, bilingue, histoires arabes, éducation des enfants, lecture interactive"
      },
      library: {
        title: "Bibliothèque",
        siteName: "Bibliothèque Jeen Arabi",
        description: "Explorez notre collection d'histoires bilingues pour enfants. Filtrez par âge, langue et sujet.",
        keywords: "bibliothèque d'histoires, livres pour enfants, lecture, éducation"
      },
      design: {
        title: "Studio de Design",
        description: "Créez vos propres histoires magiques avec notre studio de design interactif. Utilisez des autocollants, dessinez et laissez l'IA vous aider à écrire.",
        keywords: "créer des histoires, écriture pour enfants, imagination, dessin"
      },
      login: {
        title: "Connexion",
        description: "Connectez-vous à Jeen Arabi pour gérer les histoires et les abonnés.",
        keywords: "connexion, admin, tableau de bord"
      },
      support: {
        title: "Soutenez-nous",
        description: "Soutenez la mission de Jeen Arabi de fournir des histoires bilingues de haute qualité pour les enfants. Aidez-nous à développer notre bibliothèque magique.",
        keywords: "soutien, don, éducation des enfants, histoires bilingues"
      }
    },
    hero: {
      title: "Découvrez un monde d'histoires",
      subtitle: "Des aventures multilingues pour les esprits curieux. Lisez, apprenez et créez.",
      cta: "Commencer à lire",
      secondaryCta: "Créer une histoire",
      badge: "Plateforme d'apprentissage interactive",
      features: [
        { title: "Histoires bilingues", desc: "Passez de l'arabe à l'anglais instantanément.", icon: "🌍" },
        { title: "Design interactif", desc: "Créez vos propres couvertures et histoires.", icon: "🎨" },
        { title: "Sûr et sécurisé", desc: "Environnement sans publicité pour les enfants.", icon: "🛡️" }
      ]
    },
    library: {
      title: "Nos Histoires",
      filterAge: "Filtrer par âge",
      filterLang: "Filtrer par langue",
      filterTags: "Filtrer par sujet",
      read: "Lire l'histoire",
      download: "Télécharger PDF",
      all: "Tous",
      close: "Fermer",
      downloads: "Téléchargements",
      views: "Vues",
      age: "Âge",
      categories: "Catégories",
      storiesAvailable: "Histoires disponibles",
      loadingStory: "Chargement de l'histoire...",
      noFavoritesTitle: "Pas encore de favoris !",
      noFavoritesDesc: "Parcourez la bibliothèque et ajoutez aux favoris les histoires que vous aimez pour les retrouver ici.",
      noResultsTitle: "Aucune histoire trouvée",
      noResultsDesc: "Essayez de modifier vos filtres ou parcourez toutes les histoires disponibles.",
      exploreAll: "Explorer toutes les histoires",
      storyFinished: "Génial ! Vous avez terminé l'histoire ! 🎉",
      share: "Partager",
      narrator: "Narrateur",
      music: "Musique",
      zoom: "Zoom/Plein écran",
      mute: "Muet/Son",
      prevPage: "Page précédente",
      nextPage: "Page suivante",
      shareSuccess: "Lien de l'histoire copié !",
      musicError: "Veuillez interagir avec la page pour jouer de la musique",
      errorTitle: "Désolé, une erreur est survenue",
      retry: "Réessayer"
    },
    design: {
      title: "Créez votre première histoire",
      subtitle: "Ajoutez des autocollants, un titre et laissez notre IA écrire l'histoire pour vous!",
      tools: "Outils",
      addText: "Ajouter du texte",
      addSticker: "Ajouter un autocollant",
      generate: "Écrire une histoire avec l'IA",
      download: "Télécharger la couverture",
      placeholderTitle: "Mon aventure magique",
      generating: "La magie opère...",
      storyDetails: "Détails de l'histoire",
      authorName: "Nom de l'auteur",
      addElements: "Ajouter des éléments",
      text: "Texte",
      draw: "Dessiner",
      stickers: "Autocollants",
      page: "Page",
      of: "sur",
      deletePage: "Supprimer la page",
      newPage: "Nouvelle page",
      startDesigning: "Commencez à concevoir!",
      dragStickers: "Faites glisser des autocollants, ajoutez du texte ou dessinez quelque chose.",
      aiStory: "Histoire d'IA",
      drawingPad: "Tableau de dessin",
      addToStory: "Ajouter à l'histoire",
      exportPdf: "Exporter en PDF",
      generatingBtn: "Génération...",
      toastMinPage: "Vous devez avoir au moins une page.",
      promptText: "Entrez votre texte :",
      toastDrawingAdded: "Dessin ajouté à l'histoire !",
      toastGeneratingPdf: "Génération du livre PDF...",
      toastPdfDownloaded: "PDF téléchargé !",
      toastPdfFailed: "Échec de la génération du PDF",
      pdfPage: "Page",
      saveToProfile: "Enregistrer dans le profil",
      drawing: "Dessin",
      preview: "Aperçu",
      enterText: "Entrez votre texte",
      confirm: "Confirmer",
      cancel: "Annuler",
      delete: "Supprimer",
      loginToSave: "Veuillez vous connecter pour enregistrer votre création",
      enterTitle: "Veuillez saisir un titre pour l'histoire",
      savingDesign: "Enregistrement du design...",
      saveDesignSuccess: "Design enregistré dans votre profil ! ✨",
      saveDesignFail: "Échec de l'enregistrement du design",
      previewReady: "Aperçu prêt",
      pagesLabel: "Pages",
      ofLabel: "sur"
    },
    admin: {
      title: "Tableau de bord",
      stories: "Gérer les histoires",
      subscribers: "Abonnés",
      analytics: "Analytique",
      addStory: "Ajouter une histoire",
      edit: "Modifier",
      delete: "Supprimer",
      save: "Enregistrer",
      saveCategory: "Enregistrer la catégorie",
      cancel: "Annuler",
      addSubscriber: "Ajouter un abonné",
      gdprLabel: "Je confirme avoir obtenu le consentement explicite de cet utilisateur pour stocker ses données et lui envoyer des mises à jour conformément au RGPD.",
      loginTitle: "Connexion Admin",
      loginBtn: "Se connecter",
      categories: "Catégories",
      manageCategories: "Gérer les catégories",
      addCategory: "Ajouter une catégorie",
      editCategory: "Modifier la catégorie",
      nameEn: "Nom (Anglais)",
      nameAr: "Nom (Arabe)",
      descEn: "Description (Anglais)",
      descAr: "Description (Arabe)",
      availableLangs: "Langues disponibles",
      createStory: "Créer une histoire",
      editStory: "Modifier l'histoire",
      storyTitle: "Titre de l'histoire",
      storyDesc: "Description",
      ageGroup: "Groupe d'âge",
      coverImage: "Image de couverture",
      uploadCover: "Télécharger la couverture",
      users: "Utilisateurs",
      manageUsers: "Gérer les Utilisateurs",
      deleteUser: "Supprimer l'Utilisateur",
      confirmDeleteUser: "Êtes-vous sûr de vouloir supprimer cet utilisateur ?",
      deleteUserSuccess: "Utilisateur supprimé avec succès",
      deleteAdminError: "Impossible de supprimer les administrateurs",
      fetchUsersError: "Échec du chargement des utilisateurs",
      totalStories: "Total des Histoires",
      totalViews: "Total des Vues",
      activeSubscribers: "Abonnés Actifs",
      uniqueTags: "Tags Uniques",
      storyViews: "Vues des Histoires",
      ageDistribution: "Distribution par Âge",
      ageToddlers: "Tout-petits (3-5)",
      ageEarly: "Premières lectures (6-8)",
      ageYoung: "Jeunes lecteurs (9-12)",
      contentSuffix: "Contenu",
      uploadTitleCover: "Cliquez pour télécharger la couverture",
      tagsLabel: "Tags (Catégories)",
      tagNamePlaceholder: "Ajouter un tag...",
      deleteStoryConfirm: "Êtes-vous sûr de vouloir supprimer cette histoire ?",
      deleteStorySuccess: "Histoire supprimée",
      deleteStoryError: "Échec de la suppression de l'histoire",
      storySavedSuccess: "Histoire enregistrée avec succès",
      storySavedError: "Échec de l'enregistrement de l'histoire",
      uploadSuccess: "Téléchargé avec succès",
      uploadError: "Échec du téléchargement",
      uploading: "Téléversement...",
      processing: "Traitement des fichiers...",
      validationTitle: "Veuillez saisir un titre pour au moins une des langues sélectionnées.",
      validationCover: "Veuillez télécharger une image de couverture.",
      validationPdf: "Veuillez télécharger un fichier PDF.",
      searchPlaceholder: "Rechercher des histoires...",
      allCategories: "Toutes les catégories",
      anyLanguage: "N'importe quelle langue",
      reset: "Réinitialiser",
      untitled: "Sans titre",
      downloads: "Téléchargements",
      noStoriesFound: "Aucune histoire trouvée correspondant à votre recherche.",
      usersManagement: "Gestion des Utilisateurs",
      user: "Utilisateur",
      email: "E-mail",
      role: "Rôle",
      joined: "Inscrit",
      actions: "Actions",
      noUsers: "Aucun utilisateur à afficher",
      fullName: "Nom complet",
      subscribersListTitle: "Liste des abonnés",
      platformSettings: "Paramètres de la Plateforme",
      saving: "Enregistrement...",
      saveAll: "Tout enregistrer",
      supportLinks: "Liens de support",
      siteMessages: "Messages du site",
      welcomeMsgAr: "Message de bienvenue (AR)",
      welcomeMsgEn: "Message de bienvenue (EN)",
      refresh: "Actualiser"
    },
    dashboard: {
      title: "Mon Tableau de Bord",
      welcome: "Bienvenue, {name} !",
      subtitle: "Prêt pour une nouvelle aventure aujourd'hui ?",
      quickLibrary: "Parcourir la Bibliothèque",
      quickDesign: "Créer une Histoire",
      myFavorites: "Mes Favoris",
      noFavorites: "Pas encore de favoris. Commencez à explorer !",
      viewInLibrary: "Voir les Favoris dans la Bibliothèque",
      stats: "Mes Stats",
      readStories: "Histoires lues",
      myDesigns: "Mes Créations",
      tipTitle: "Conseil du jour",
      tipContent: "Lire 15 minutes par jour ouvre des horizons d'imagination !",
      settings: "Paramètres du compte",
      readingMinutes: "Minutes de lecture",
      completedStories: "Histoires terminées",
      continueReading: "Continuer la lecture",
      startNow: "Commencer",
      page: "Page",
      scrollToTop: "Retour en haut",
      friend: "Ami",
      goToLibrary: "Aller à la bibliothèque"
    },
    footer: {
      privacy: "Politique de Confidentialité",
      terms: "Conditions d'Utilisation",
      rights: "Tous droits réservés à la Bibliothèque Jeen Arabi"
    },
    support: {
      title: "Soutenez Notre Voyage Magique",
      parentTitle: "Soutenez le Voyage Magique des Histoires",
      subtitle: "Nous croyons que tout le monde mérite une histoire magique qui l'inspire. Votre soutien nous aide à offrir plus de créativité et de connaissances gratuitement pour tous.",
      parentSubtitle: "Votre soutien ne fait pas que développer la plateforme ; il garantit que les histoires magiques restent accessibles aux enfants du monde entier, avec un accent particulier sur les enfants arabophones.",
      methodCoffee: "Achetez-moi un café",
      methodCoffeeDesc: "Un moyen simple et rapide de soutenir la continuité de nos histoires.",
      methodCoffeeBtn: "Soutenir avec un café",
      methodPaypal: "Faire un don via PayPal",
      methodPaypalDesc: "Soutien direct et sécurisé pour contribuer au développement de la plateforme.",
      methodPaypalBtn: "Faire un don",
      methodShare: "Partagez la Magie",
      methodShareDesc: "Partagez la plateforme avec vos amis et votre famille pour nous soutenir.",
      methodShareBtn: "Partager le site",
      impactTitle: "Pourquoi soutenir Jeen Arabi ?",
      impactDesc: "Chaque don, aussi petit soit-il, contribue aux frais d'hébergement, au développement de nouvelles fonctionnalités et à la fourniture d'un contenu éducatif de haute qualité pour les enfants du monde entier.",
      footerMsg: "Merci de faire partie de notre communauté magique ✨"
    },
    register: {
      title: "Créer un compte",
      subtitle: "Rejoignez le monde magique de Jeen Arabi",
      username: "Nom d'utilisateur",
      email: "Adresse e-mail",
      password: "Mot de passe",
      btn: "Créer un compte",
      alreadyHave: "Vous avez déjà un compte ?",
      login: "Se connecter",
      success: "Compte créé avec succès ! Bienvenue ✨"
    },
    settings: {
      title: "Paramètres du Compte",
      personalInfo: "Informations Personnelles",
      username: "Nom d'utilisateur",
      email: "Adresse e-mail",
      changePassword: "Changer le mot de passe",
      oldPassword: "Mot de passe actuel",
      newPassword: "Nouveau mot de passe",
      confirmPassword: "Confirmer le nouveau mot de passe",
      updateBtn: "Mettre à jour le profil",
      passwordBtn: "Mettre à jour le mot de passe",
      successProfile: "Profil mis à jour avec succès !",
      successPassword: "Mot de passe mis à jour avec succès !",
      errorMatch: "Les mots de passe ne correspondent pas",
      dangerZone: "Zone de Danger",
      deleteAccount: "Supprimer le compte",
      deleteWarning: "Une fois que vous supprimez votre compte, il n'y a pas de retour en arrière. Soyez certain."
    }
  }
};

// export const MOCK_STORIES: Story[] = [
//   {
//     id: '1',
//     title: { en: "The Little Star", ar: "النجمة الصغيرة", fr: "La Petite Étoile" },
//     description: { en: "A journey of a star finding its glow.", ar: "رحلة نجمة تبحث عن بريقها.", fr: "Le voyage d'une étoile cherchant sa lueur." },
//     coverImage: "https://picsum.photos/400/600?random=1",
//     pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
//     ageGroup: '3-5',
//     categoryLabel: 'Bilingual',
//     availableLanguages: ['en', 'ar', 'fr'],
//     tags: ['Space', 'Kindness'],
//     views: 1205,
//     downloads: 340
//   },
//   {
//     id: '2',
//     title: { ar: "دراجة عمر الحمراء" },
//     description: { ar: "عمر يتعلم ركوب دراجته." },
//     coverImage: "https://picsum.photos/400/600?random=2",
//     pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
//     ageGroup: '6-8',
//     categoryLabel: 'Arabic',
//     availableLanguages: ['ar'],
//     tags: ['Sports', 'Courage'],
//     views: 980,
//     downloads: 125
//   },
//   {
//     id: '3',
//     title: { en: "The Hidden Garden" },
//     description: { en: "Discovering magic in the backyard." },
//     coverImage: "https://picsum.photos/400/600?random=3",
//     pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
//     ageGroup: '9-12',
//     categoryLabel: 'English',
//     availableLanguages: ['en'],
//     tags: ['Nature', 'Mystery'],
//     views: 450,
//     downloads: 88
//   },
//   {
//     id: '4',
//     title: { en: "Layla and the Moon", ar: "ليلى والقمر", fr: "Layla et la Lune" },
//     description: { en: "A bedtime story about friendship.", ar: "قصة ما قبل النوم عن الصداقة.", fr: "Une histoire du soir sur l'amitié." },
//     coverImage: "https://picsum.photos/400/600?random=4",
//     pdfUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
//     ageGroup: '3-5',
//     categoryLabel: 'Bilingual',
//     availableLanguages: ['en', 'ar', 'fr'],
//     tags: ['Bedtime', 'Friends'],
//     views: 2100,
//     downloads: 542
//   }
// ];

export const STICKERS = [
  { id: 's1', icon: '🌟', name: 'Star' },
  { id: 's2', icon: '🚀', name: 'Rocket' },
  { id: 's3', icon: '🐱', name: 'Cat' },
  { id: 's4', icon: '🌳', name: 'Tree' },
  { id: 's5', icon: '🏰', name: 'Castle' },
  { id: 's6', icon: '🐲', name: 'Dragon' },
];